# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import distripute_pb2 as distripute__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in distripute_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MasterStub(object):
    """── Services ────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/distripute.Master/Register',
                request_serializer=distripute__pb2.RegisterRequest.SerializeToString,
                response_deserializer=distripute__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/distripute.Master/Heartbeat',
                request_serializer=distripute__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=distripute__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.PollTasks = channel.unary_unary(
                '/distripute.Master/PollTasks',
                request_serializer=distripute__pb2.PollRequest.SerializeToString,
                response_deserializer=distripute__pb2.PollResponse.FromString,
                _registered_method=True)
        self.SubmitResult = channel.unary_unary(
                '/distripute.Master/SubmitResult',
                request_serializer=distripute__pb2.TaskResult.SerializeToString,
                response_deserializer=distripute__pb2.Ack.FromString,
                _registered_method=True)
        self.SubmitTask = channel.unary_unary(
                '/distripute.Master/SubmitTask',
                request_serializer=distripute__pb2.TaskSubmit.SerializeToString,
                response_deserializer=distripute__pb2.TaskSubmitResponse.FromString,
                _registered_method=True)
        self.GetTaskResult = channel.unary_unary(
                '/distripute.Master/GetTaskResult',
                request_serializer=distripute__pb2.TaskResultRequest.SerializeToString,
                response_deserializer=distripute__pb2.TaskResultResponse.FromString,
                _registered_method=True)
        self.CreateBatch = channel.unary_unary(
                '/distripute.Master/CreateBatch',
                request_serializer=distripute__pb2.BatchCreateRequest.SerializeToString,
                response_deserializer=distripute__pb2.BatchCreateResponse.FromString,
                _registered_method=True)
        self.GetBatchStatus = channel.unary_unary(
                '/distripute.Master/GetBatchStatus',
                request_serializer=distripute__pb2.BatchStatusRequest.SerializeToString,
                response_deserializer=distripute__pb2.BatchStatusResponse.FromString,
                _registered_method=True)
        self.GetFile = channel.unary_stream(
                '/distripute.Master/GetFile',
                request_serializer=distripute__pb2.FileRequest.SerializeToString,
                response_deserializer=distripute__pb2.FileChunk.FromString,
                _registered_method=True)
        self.UploadFile = channel.stream_unary(
                '/distripute.Master/UploadFile',
                request_serializer=distripute__pb2.FileChunk.SerializeToString,
                response_deserializer=distripute__pb2.FileUploadResponse.FromString,
                _registered_method=True)
        self.RegisterModel = channel.unary_unary(
                '/distripute.Master/RegisterModel',
                request_serializer=distripute__pb2.ModelRegisterRequest.SerializeToString,
                response_deserializer=distripute__pb2.Ack.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/distripute.Master/ListModels',
                request_serializer=distripute__pb2.Empty.SerializeToString,
                response_deserializer=distripute__pb2.ModelListResponse.FromString,
                _registered_method=True)
        self.GetInfo = channel.unary_unary(
                '/distripute.Master/GetInfo',
                request_serializer=distripute__pb2.Empty.SerializeToString,
                response_deserializer=distripute__pb2.InfoResponse.FromString,
                _registered_method=True)


class MasterServicer(object):
    """── Services ────────────────────────────────────────────

    """

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBatchStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=distripute__pb2.RegisterRequest.FromString,
                    response_serializer=distripute__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=distripute__pb2.HeartbeatRequest.FromString,
                    response_serializer=distripute__pb2.HeartbeatResponse.SerializeToString,
            ),
            'PollTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.PollTasks,
                    request_deserializer=distripute__pb2.PollRequest.FromString,
                    response_serializer=distripute__pb2.PollResponse.SerializeToString,
            ),
            'SubmitResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitResult,
                    request_deserializer=distripute__pb2.TaskResult.FromString,
                    response_serializer=distripute__pb2.Ack.SerializeToString,
            ),
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=distripute__pb2.TaskSubmit.FromString,
                    response_serializer=distripute__pb2.TaskSubmitResponse.SerializeToString,
            ),
            'GetTaskResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskResult,
                    request_deserializer=distripute__pb2.TaskResultRequest.FromString,
                    response_serializer=distripute__pb2.TaskResultResponse.SerializeToString,
            ),
            'CreateBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBatch,
                    request_deserializer=distripute__pb2.BatchCreateRequest.FromString,
                    response_serializer=distripute__pb2.BatchCreateResponse.SerializeToString,
            ),
            'GetBatchStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBatchStatus,
                    request_deserializer=distripute__pb2.BatchStatusRequest.FromString,
                    response_serializer=distripute__pb2.BatchStatusResponse.SerializeToString,
            ),
            'GetFile': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=distripute__pb2.FileRequest.FromString,
                    response_serializer=distripute__pb2.FileChunk.SerializeToString,
            ),
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=distripute__pb2.FileChunk.FromString,
                    response_serializer=distripute__pb2.FileUploadResponse.SerializeToString,
            ),
            'RegisterModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModel,
                    request_deserializer=distripute__pb2.ModelRegisterRequest.FromString,
                    response_serializer=distripute__pb2.Ack.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=distripute__pb2.Empty.FromString,
                    response_serializer=distripute__pb2.ModelListResponse.SerializeToString,
            ),
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=distripute__pb2.Empty.FromString,
                    response_serializer=distripute__pb2.InfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distripute.Master', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distripute.Master', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Master(object):
    """── Services ────────────────────────────────────────────

    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distripute.Master/Register',
            distripute__pb2.RegisterRequest.SerializeToString,
            distripute__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distripute.Master/Heartbeat',
            distripute__pb2.HeartbeatRequest.SerializeToString,
            distripute__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distripute.Master/PollTasks',
            distripute__pb2.PollRequest.SerializeToString,
            distripute__pb2.PollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distripute.Master/SubmitResult',
            distripute__pb2.TaskResult.SerializeToString,
            distripute__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distripute.Master/SubmitTask',
            distripute__pb2.TaskSubmit.SerializeToString,
            distripute__pb2.TaskSubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distripute.Master/GetTaskResult',
            distripute__pb2.TaskResultRequest.SerializeToString,
            distripute__pb2.TaskResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distripute.Master/CreateBatch',
            distripute__pb2.BatchCreateRequest.SerializeToString,
            distripute__pb2.BatchCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBatchStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distripute.Master/GetBatchStatus',
            distripute__pb2.BatchStatusRequest.SerializeToString,
            distripute__pb2.BatchStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/distripute.Master/GetFile',
            distripute__pb2.FileRequest.SerializeToString,
            distripute__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/distripute.Master/UploadFile',
            distripute__pb2.FileChunk.SerializeToString,
            distripute__pb2.FileUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distripute.Master/RegisterModel',
            distripute__pb2.ModelRegisterRequest.SerializeToString,
            distripute__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distripute.Master/ListModels',
            distripute__pb2.Empty.SerializeToString,
            distripute__pb2.ModelListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distripute.Master/GetInfo',
            distripute__pb2.Empty.SerializeToString,
            distripute__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RelayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/distripute.Relay/Connect',
                request_serializer=distripute__pb2.RelayFrame.SerializeToString,
                response_deserializer=distripute__pb2.RelayFrame.FromString,
                _registered_method=True)


class RelayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RelayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=distripute__pb2.RelayFrame.FromString,
                    response_serializer=distripute__pb2.RelayFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distripute.Relay', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distripute.Relay', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Relay(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/distripute.Relay/Connect',
            distripute__pb2.RelayFrame.SerializeToString,
            distripute__pb2.RelayFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
